- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:DepartmentTimeRequirement
      department: CentralCommand
      time: 20h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 75h
    - !type:RoleTimeRequirement
      department: Security
      time: 15h
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups: # THIS IS IN ALPHABETICAL ORDER, KEEP IT IN ALPHABETICAL ORDER.
  - Brig
  - Cargo
  - CentralCommand
  - Command
  - Cryogenics
  - Engineering
  - External
  - GenpopEnter
  - GenpopLeave
  - Lawyer
  - Maintenance
  - Medical
  - Research
  - Security
  - Service
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  alternateTitles:
  - MagistrateArbitrator
  - MagistrateChiefLegalOfficer
  - MagistrateJudge
  - MagistrateJudicialAdministrator
  - MagistrateNanotrasenChiefAdjudicator

- type: startingGear
  id: MagistrateGear
    belt: ClothingBeltStorageWaistbag
    ears: ClothingHeadsetAltCentCom
    eyes: ClothingEyesGlassesSecurity
    id: MagistratePDA
    pocket2: RubberStampMagistrate
  storage:
    back:
    - BluespaceLifelineImplanter
    - BookSpaceLaw
    - BoxFolderCentComClipboard
    - Flash

- type: jobAlternateTitle
  id: MagistrateJudge
  name: job-name-alt-magistrate-1

- type: jobAlternateTitle
  id: MagistrateArbitrator
  name: job-name-alt-magistrate-2

- type: jobAlternateTitle
  id: MagistrateNanotrasenChiefAdjudicator
  name: job-name-alt-magistrate-3

- type: jobAlternateTitle
  id: MagistrateJudicialAdministrator
  name: job-name-alt-magistrate-4

- type: jobAlternateTitle
  id: MagistrateChiefLegalOfficer
  name: job-name-alt-magistrate-5
