- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - Magistrate
  - NanotrasenRepresentative
  - InternalAffairsAgent
  weight: 110